baseURL = "https://jacoblincool.github.io/leetcode-blog/"
languageCode = "zh-tw"
DefaultContentLanguage = "zh-tw"
title = "Leetcode Story"
theme = "ananke"


# === TRANSLATIONS ===
[Languages]

[Languages.zh-tw]
  languageCode  = "zh-tw"
  languageName  = "正體中文（臺灣）"

# [Languages.en]
#   languageCode  = "en"
#   languageName  = "English"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true