name: Hugo Build & Deploy CI
on: push
jobs:
  build_and_deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.16.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Hugo
      run: sudo apt-get install hugo
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GH_TOKEN }}
    - name: Hugo Build Site
      run: hugo -D
    - uses: peaceiris/actions-gh-pages@v3.7.3
      name: GitHub Page Deploy
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: "./public"
        user_name: "JacobLinCool"
        user_email: "jacoblincool@users.noreply.github.com"